// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using CakesByRAndRCore.Models;

namespace CakesByRAndRCore.Data
{
    public partial class CakesByRAndRCoreContext : DbContext
    {
        public CakesByRAndRCoreContext()
        {
        }

        public CakesByRAndRCoreContext(DbContextOptions<CakesByRAndRCoreContext> options)
            : base(options)
        {
        }

        public virtual DbSet<CakeCategory> CakeCategories { get; set; }
        public virtual DbSet<TaskItem> TaskItems { get; set; }



        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}